name: deck_it
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^11.0.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  flutter_timezone: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"