// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/card_sr_data.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 877715863525900315),
    name: 'CardSRData',
    lastPropertyId: const obx_int.IdUid(7, 1934402273472915875),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6542599694320889339),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7873669192526041488),
        name: 'cardId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 1670873504246388868),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3370172467595172100),
        name: 'repetitions',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2673032770239845994),
        name: 'easeFactor',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1665470258457252995),
        name: 'intervalDays',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 846024657923424424),
        name: 'nextReviewDate',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1934402273472915875),
        name: 'lastReviewDate',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 877715863525900315),
    lastIndexId: const obx_int.IdUid(1, 1670873504246388868),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CardSRData: obx_int.EntityDefinition<CardSRData>(
      model: _entities[0],
      toOneRelations: (CardSRData object) => [],
      toManyRelations: (CardSRData object) => {},
      getId: (CardSRData object) => object.id,
      setId: (CardSRData object, int id) {
        object.id = id;
      },
      objectToFB: (CardSRData object, fb.Builder fbb) {
        final cardIdOffset = fbb.writeString(object.cardId);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, cardIdOffset);
        fbb.addInt64(2, object.repetitions);
        fbb.addFloat64(3, object.easeFactor);
        fbb.addInt64(4, object.intervalDays);
        fbb.addInt64(5, object.nextReviewDate?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.lastReviewDate?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nextReviewDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final lastReviewDateValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final cardIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final repetitionsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final easeFactorParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final intervalDaysParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final nextReviewDateParam = nextReviewDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(nextReviewDateValue);
        final lastReviewDateParam = lastReviewDateValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastReviewDateValue);
        final object = CardSRData(
          id: idParam,
          cardId: cardIdParam,
          repetitions: repetitionsParam,
          easeFactor: easeFactorParam,
          intervalDays: intervalDaysParam,
          nextReviewDate: nextReviewDateParam,
          lastReviewDate: lastReviewDateParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CardSRData] entity fields to define ObjectBox queries.
class CardSRData_ {
  /// See [CardSRData.id].
  static final id = obx.QueryIntegerProperty<CardSRData>(
    _entities[0].properties[0],
  );

  /// See [CardSRData.cardId].
  static final cardId = obx.QueryStringProperty<CardSRData>(
    _entities[0].properties[1],
  );

  /// See [CardSRData.repetitions].
  static final repetitions = obx.QueryIntegerProperty<CardSRData>(
    _entities[0].properties[2],
  );

  /// See [CardSRData.easeFactor].
  static final easeFactor = obx.QueryDoubleProperty<CardSRData>(
    _entities[0].properties[3],
  );

  /// See [CardSRData.intervalDays].
  static final intervalDays = obx.QueryIntegerProperty<CardSRData>(
    _entities[0].properties[4],
  );

  /// See [CardSRData.nextReviewDate].
  static final nextReviewDate = obx.QueryDateProperty<CardSRData>(
    _entities[0].properties[5],
  );

  /// See [CardSRData.lastReviewDate].
  static final lastReviewDate = obx.QueryDateProperty<CardSRData>(
    _entities[0].properties[6],
  );
}
